# name: 'Hello World'
# description: 'Greet someone and record the time'
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
# runs: 
#   main: ./.yamllint.yml
# workflow_run:
#   workflows: ["linter"]
# # runs:
# #   using: 'node12'
# #   main: 'dist/index.js'
name: linter

extends: default

ignore: |
  /node_modules/

rules:
  line-length: 
    max: 120
  document-start: disable
  truthy: disable
  trailing-spaces: disable