name: Yaml Lint

on:
  push:
  pull_request:
    commit-ignore:
      - [skip ci]
      - [ci skip]

jobs:
  lintAllTheThings:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yml